spring:
  profiles:
    active: dev

  datasource:
    name: emall
    url: jdbc:mysql://127.0.0.1:3306/recruitment?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: meijinzhi159.
    type: com.alibaba.druid.pool.DruidDataSource
    drive-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
  mail:
    #QQ邮箱这不用改
    host: smtp.qq.com
    #你的邮箱
    username: 1273553264@qq.com
    #你的授权码
    password: ezywncqvxxyogdai
    default-encoding: UTF-8
  redis:
    #redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    jedis:
      pool:
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 0
        #连接超时时间（毫秒）
    timeout: 60000

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.meijinzhi.entity
  configuration:
    mapUnderscoreToCamelCase: true
server:
  port: 8080

alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appid: 2021000119658119
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCsvelCvSvOzozmvckiAgGsRcF0FTNiDIkXVayvsyesSNM4s45OVNbhrVeqhhKacR+w0aQhyVwsL+CboH4i5qGl/riG0d1rwp+NeWHdtkrPpKRFTd0kEB4twmVobxZEhLpb+KOSN93OcNROHuad+u3/hiAiWtbsMrahqr8fGqsABLV++/2lYp6dfacQYCFrqHRIKGxHV2SEUC163ZMz+pHssZMzSdxZkKpIINuYXPBF5x2Zi+3VUjNBDmXrfI0hQd8Q3HLzgR6BM/KGp3I3BvlzkFrjSEV2RNo1f/EKf3FjyHAS+xXNZHZ/BTtywaZMj81fO1LFa+v92B0hzL/tT6yVAgMBAAECggEBAJSSVsDXEYmy7086JncAgM3ZxTSBU4teOr7+KiOIFHRCwqC/FoNaxuKdg4wf+nopF9etx9xjYsqCd02DMVn1QU0TE0Sp1iZr42z73Gej9R44fi05dh0hW8OBslSrTtypx9t4s778G+MF+iQiwblY7EBc7OB/fuDyEVBlGjK3biH5eoQY+VfHq1U1fCVpBjgnce+awCf9fJN1RAAtVc8LSnxdDajlJdNrQKeqSJlPsJqxwZucHCXHbkeTfI5G0nfn2o0zZkEegvprzABg2Q3EkZkMpFPFlZ4f46mdBnnpFQyUBEYU0VfIIAVavm/fFFxY/u5lKUYiMGOLzcEdQDDap4ECgYEA/oPdDu8Nd4tIlERnNR/5Yxy/PSi7FLBX8Kz83eCwYQGmMv9YFfX772vmWerB748S6iw4+O27VVpS2LJ6kcN5/dkJunw3Vcci6CG35VH9LYoopnDraV0rXq2D/Yx46LIsyxtKwVSGmati7N37/6VpArygNKzb7GzQ4+gIBYRHsXUCgYEArb/p2PVytZIpE8hki0MdgZ3NnpiNJjC2EDnLlvHGeKjrfkKHUdHvGYEffv7w2rCKptxh9XkNOhMId/t+ZJNB5glZNyFxV29wX21UVR2eusvCtFl3OhWmbfVaefUnx3TiuN03CvsRyvr2Gy0AdJVsfb9gf/MGBlNiIfawJNpQiqECgYBM+LwmBA3ilXEBxh4gZucZHlyHtoW9oAc4dliTEZzF+aW1zptpKNdkdRFZKDI2rOJfh7hDMEJzcbmUZ4XCB4ghST4z89UYT/0yjt/6rm0PFLVugL/xQYgYPgmo6I64cQoy8rIM/e8nEjn8wLWxfujfNwSMaaqpOc+C3W1vna3A8QKBgQCtIyJJujx2RpF8TyIxy81pTfCJ64Yr2jpybMU9Quv9bIZOKMljdQkHpy3VhQJJScbAg7dxvxC5ICI+PXQzkLIIIqSuVTr2X+vgi7ePoZZ8mXMJ+GTgkpZn2Cgyg2MCVK1gfb/Nx2ZxmCcJ6YwcoJGdtMjadzc3snuFUKcx8gJ0QQKBgQCdrLkpaglfNalO8ndwif3GOOxuphDvIQB4BPC51d/M1L7qM1W2xchyfg2ntdE3gAJwj0p7S9wQDsMlE6ahG0sj8Wf4LTkFI9QmJAYkYIOqe/ZUCMgY/cJrUEngHcBH46by2E/Ncmf7iCd6BrA4PUPhqgKPSO+13L7KReq+FDEGmQ==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmyoqP10+5zdYsDPfDwf24/aQHJhlAChSpFHX+wnB/L92K2yG/icBp7nUQ113SPAPeT/u7nVPNuqJm5VVnqxmZoij7t59cNl7g3PP20MYhVRUROl0RE4TEjuOFm53IA+8Sn6hlAZrXhSZ3TMVHXLHK31nvoEb6Whav40uRtobpLDwbjPX9eFenV9TPo15V8luhqoK+CXVqp1AyUVolxk/Wog3mWCFq8dh6hab9ww5vPo0tzoqq3zevKoXtRxF1Ecvd+VDA9EGfU5EjMRYjezdjh8OPuXtU/LUdPaI75z1/+APNVcswRGRKvyRfq7dBaUZe1lGEEb8Vah7rCIIQcS06QIDAQAB
  notifyUrl: http://localhost:8080/buy/notify
  returnUrl: http://localhost:8080/buy/return
